---
title: 'Mapping population data'
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
urlcolor: blue
vignette: >
  %\VignetteIndexEntry{Mapping population data} 
  %\VignetteEngine{knitr::rmarkdown} 
  \usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

Spatial distribution of population


```{r, message = FALSE, eval = FALSE}
# load libraries
library(aopdata)
library(data.table)
library(ggplot2)
library(sf)
library(scales)

```

**Download population data**
```{r, message = FALSE, eval = FALSE}

# download aop data
df <- read_population(city='Fortaleza',
                      year=2010,
                      geometry = T,
                      showProgress = F)

```

**Map Population**
Spatial distribution of the population

```{r, message = FALSE, eval = FALSE}
ggplot() +
  geom_sf(data=subset(df, P001>0), aes(fill=P001), color=NA, alpha=.8) +
  scale_fill_distiller(palette = "YlOrRd", direction = 1)+
  labs(title='Population distribution', fill="Total population") +
  theme_void()

```

**Map income levels**
Spatial distribution population by income decile

```{r, message = FALSE, eval = FALSE}
ggplot() +
  geom_sf(data=subset(df, !is.na(R002)), aes(fill=factor(R003)), color=NA, alpha=.8) +
  scale_fill_brewer(palette = "RdBu") +
  labs(title='Average household income per capita', fill="Income decile") +
  theme_void()

```


**Map racial groups**
Spatial distribution population black population

```{r, message = FALSE, eval = FALSE}
df$prop_black <- df$P003 / df$P001
  
ggplot() +
  geom_sf(data=subset(df, P001 >0), aes(fill=prop_black), color=NA, alpha=.8) +
  scale_fill_distiller(palette = "RdPu", direction = 1, labels = percent)+
  labs(title='Proportion of black population', fill="Black population") +
  theme_void()

```

