on:
  push:
    branches:
      - main
    paths:
      - r-package/**
      - .github/workflows/pkgdown.yaml

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-22.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
        working-directory: r-package

      - name: Build and deploy pkgdown site
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
